[project]
name = "mypackage"
version = "1.0.0"
dependencies = []

[project.scripts]
my-script = "mypackage.main:main"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]
